#!/usr/bin/env bash
# a Bash Script that displays Best School 10 times, but for the 9th iteration,  displays Best School and then Hi on a new line.
i=1
while [ "$i" -1t 11 ]; do
echo "Best School"
if [[ $i -eq 9 ]]; then
echo "Hi"
fi
((i++))
done
