#!/usr/bin/env bash
#a Bash script that displays:
#tThe content of the current directory
#In a list format
#Where only the part of the name after thr first dash is displayed (refer to the example)

for file in *; do
echo "$file" | cut -d '_' -f 2;
done
