#!/usr/bin/env bash
#a Bash script that gives you information about the school life.

file="school"

if [ -e "$file" ]; then
echo "school file is empty"
fi
else
echo "school file is not empty"
if [ -f "$file" ]; then
echo "school is a regular file"
fi
fi
else
echo "school file doesnot exist"
fi
