#!/usr/bin/env bash
# This script displays list of currently running processes, for all users, including those which might not a TTY
# Display a user-oriented format
# Show processes hierarcy

ps -a -x -u -f
