#!/usr/bin/env bash
# This a bash script displays:

# To infinity and beyond
# with a sleep 2 in between ech iteration
# I am invincible !!! when recieving a SIGTERM signal

trap "echo I am invincible!!!"' 15

while true; do
echo "to infinity and beyond"
sleep 2
done
